### ISSUE TITLE
Crash on runtime in --prod

### ISSUE THREAD

**Issue by narrowfail** [narve/angular-bpmn#15]
Any idea of why it crashes on runtime?

**Comment by narrowfail** [comment]
Changed title

**Comment by cybergeene** [comment]
Same issue, may I help with it, narve?

**Comment by narve** [comment]
This is due to the Angular javascript-minification - the name of the variables are minified, e.g. "paletteProvider" becomes "e". 

I really haven't spent much time researching this - I just skipped the "production" mode. The whole "production" mode and javascript minification (and Angular in general:D) is just plain stupid so I don't want to waste my limited brain power on these issues :)

**Comment by narve** [comment]
Having said that, I've just migrated my main project to Angular 7 (the Github project was just an experiment to set things up), and everything worked rather smoothly. Possibly even the --prod mode. I'll check it out week after next when I'm back at work and comment here.

**Comment by dangviettuan** [comment]
Hi guys. I tried production build but cannot see any error. How to reproduce?

**Comment by narrowfail** [comment]
Builds ok, crashes on runtime.

**Comment by dangviettuan** [comment]
I tried replace 
import _Modeler from 'bpmn-js/lib/Modeler.js';
by 
import * as _Modeler from "bpmn-js/dist/bpmn-modeler.production.min.js";
Build success and no crash on runtime.

**Comment by narve** [comment]
Surprisingly that works perfectly, nice catch, @dangviettuan !! I'll push a patch immediately.

**Comment by narve** [comment]
Pushed, thanks again :)
